[Feat] 상품 구성하기 페이지 및 api 연동
k-roffle/knitting-frontend pull request #113
Opened 2021-10-08 03:50 UTC by jiyaaany

## PR 제안 사유
- 상품 등록 절차 중 상품 구성하기 페이지를 추가합니다.
- 상품 구성하기 api `/product/package` 를 연동합니다.

Resolve #112 

## 주요 변경 기록
- `/my/products/create` 라우터 추가
- `/product/package` api 연동

## 기타 질문 및 특이 사항
대표 이미지 업로드하는 부분에 `FileUploader`가 들어갈거라 추후 작업이 필요합니당.
지금은 그냥 아무 업로더 하나 넣어뒀어요 ~
![image](https://user-images.githubusercontent.com/43168524/136495323-20cf598e-6ba9-48dd-bd9d-2a8b21269c86.png)

2021-10-10 06:45 UTC, YuuRiLee commented
오잉 깃헙 로그인 안 한건가유?

2021-10-10 07:36 UTC, YuuRiLee requested changes
고생하셨습니다!! 코멘트 확인 부탁드려요

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/components/Header/index.tsx
> +  const renderTitles = (): string => {
p3: title을 render하는 함수를 각각 만들지 말고 renderContents 이런걸 만들어서 `const {title, detailContents} = renderContents` 이렇게 하는게 낫지 않을까요?

2021-10-10 07:36 UTC, YuuRiLee commented on package.json
> +    "@date-io/date-fns": "^2.11.0",
p5: saso or tmi 저는 패키지 추가하는거는 feat 대신 chore 써용
https://doublesprogramming.tistory.com/256

2021-10-10 07:36 UTC, YuuRiLee commented on src/dumbs/InlineInput/index.tsx
> +interface Props {
Q: InputBaseComponentProps나 input extends 못 받나요?

2021-10-10 07:36 UTC, YuuRiLee commented on src/dumbs/InlineInput/index.tsx
> +  inputProps?: InputBaseComponentProps;
Q: inputProps를 따로 받는 이유가 궁금합니담

2021-10-10 07:36 UTC, YuuRiLee commented on src/dumbs/InlineInput/index.tsx
> +    <InputGrid container item alignItems={'center'}>
p3: `alignItems='center'` 괄호 지워주세유

2021-10-10 07:36 UTC, YuuRiLee commented on src/dumbs/InlineInput/index.tsx
> +          id={id}
p3: 아래처럼은 어떠신가요? 그러면 

```
const InlineInput = ({
  id,
  label,
  variant,
  ...other
}: Props)
```
`<Input {...other}/>`

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +  color: ${(props) => (props.isInvalid ? '#ff0000' : '#808080')};
Q:  palette에 없나요? 없다면 추가해주세요

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +  const renderSalesDateInfoMessage = (): ReactNode => {
p3: else 문이 많아지니 조금 복잡해지는 것 같네요

아래 방법 2가지 제안합니다!
방법 1: switch true pattern  https://ui.toast.com/weekly-pick/ko_20210603
방법 2: 조건문 if문으로만 쓰기

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +      if (
p3: 이 조건은 const로 빼면 더 직관적으로 알 수 있을 것 같아요

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +        isInvalid = true;
p2: 아래 코드 다시 보고 오니까 여기 invalid랑 그냥 안내 메시지랑 둘 다 여기 함수에서 해주는군욤 invalid는 따로 분리해주는게 좋을 것 같아요

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +    return currentProductInput.fullPrice - currentProductInput.discountPrice;
Q: 음수가 나올 수도 있지 않을까요?

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +        {/* <Grid item xs={12}>*/}
p2: 필요없는 코드라면 삭제하고 커밋해주세요!

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +            {getRate() && (
p3: getRate 함수를 2번 호출할 필요가 있을까요? 위에서 const rate = getRate() 이런식으로 먼저 선언해버리면 어떨까요?

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +          <img src="//via.placeholder.com/100x100" loading="lazy" />
Q: 이건 그냥 임시로 넣어두신거죠?

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +                invalidDateMessage=""
Q: 이건 꼭 넣어줘야 하나요? 빈 값으로 넣어주셔서 여쭤봅니담

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/recoils.ts
> +    tags: [''],
Q: 초기값이 빈 배열이 아닌 이유가 궁금해요

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/Package/index.tsx
> +      <SalesDateInfo variant="h5" fontcolor={fontColor}>
Q: fontcolor 보다는 이전처럼 isInvalid로 받는게 더 좋아보이는데 바꾸신 이유가 있으신가요?

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/components/Footer/index.tsx
> +      window.location.reload();
Q: 왜 리로드를 하나욤??? 리스트로 가야하지 않을까요?

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/components/Footer/index.tsx
> +    await request({
p2: axios 말고 react-query 사용해주세요!

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/components/Footer/index.tsx
> +      data: {
p3: data 포멧팅은 보낼 때 말고 이 위에서 포멧팅 해주는게 좋을 것 같아요

2021-10-10 07:36 UTC, YuuRiLee commented on src/pages/CreateProduct/components/Footer/index.tsx
> +  const [openErrorSnackbar, setOpenErrorSnackbar] = useState(false);
p2: useCommonSnackbar 라는 훅이 있습니당!

2021-10-13 02:47 UTC, jiyaaany commented on src/pages/CreateProduct/Package/index.tsx
> +  const renderSalesDateInfoMessage = (): ReactNode => {
switch true 패턴으로 바꾸면서 이런 문제가 발생해서 2번 방법으로 할게요 ! (아래 문제를 해결하는 방법을 알고 있다면 알려주세유 😂)
![image](https://user-images.githubusercontent.com/43168524/137058157-20a35eac-2773-49b0-a588-b4cd88e65cf9.png)
조건문의 실행문에서 조건을 체크하지 못하고 있는 것 같아유
위 같은 경우는 `specifiedSalesStartDate`와 `specifiedSalesEndDate`가 있는 조건문임에도
실행문에서 `specifiedSalesStartDate`, `specifiedSalesEndDate` 값이 null일 수 있다고 말해주는 에러입니다.

2021-10-13 04:01 UTC, jiyaaany commented on src/pages/CreateProduct/Package/index.tsx
> +                invalidDateMessage=""
어떤거 ㅅ때문에 넣어줬던걸로 기억하는데 ,, 어떤건지 기억이 ,, 
제거해도 작동 잘 되는 것 같아서 제거했슴당

2021-10-13 05:54 UTC, closed without merging