[WIP][Feat] 새로운 도안 작성하기 - 기본 정보 입력 페이지 상태 관리
k-roffle/knitting-frontend pull request #24
Opened 2021-04-03 03:09 UTC by kimdoori

## 체크리스트

아래 리스트를 체크해보시고, 전부 다 확인하셨다면 지워주세요.

- [ ] 이슈를 먼저 생성했는지 확인하기.
- [ ] PR 제목에 PR 내용에 대한 prefix를 넣었는지 확인하기.
- [ ] 본문에 close issue prefix와 이슈 번호를 넣었는지 확인하기.
- [ ] 배포되었을 때 UI 상에서 달라지는 부분이 있다면 스크린샷/스크린 캐스트 첨부했는지 확인하기.

## PR 제안 사유

[키워드] #[이슈번호]

## 주요 변경 기록

## Code review

### Code review 에서 중점적으로 봐야하는 부분

## Design review

### Design review 에서 중점적으로 봐야하는 부분 / 스크린샷

## 기타 질문 및 특이 사항

2021-04-04 02:22 UTC, zoripong requested changes

2021-04-04 02:22 UTC, zoripong commented on src/pages/CreateDesign/types.ts
> +};
Design 아래에 detail과 pattern으로 구분되는 것 아닌가요?
**Detail**Inputs 타입 안에 pattern도 포함되어있어서 질문드립니다!
pattern을 포함시키려면 DetailInputs이라는 이름보다 DesignInputs이라는 네이밍이 더 좋지 않을까요?

참고로 이전에 논의했던 워딩에 대한 정리는 아래에서 확인할 수 있습니다!(별거 안적혀있지만..):
https://www.notion.so/wordway/Ubiquitous-Language-7ed8e229bcec4a6eb160501192eb08e0

2021-04-04 02:22 UTC, zoripong commented on src/pages/CreateDesign/recoils.ts
> +    armLength: 0,
p2: 요 워딩 서버측 워딩이랑 통일하면 좋을 것 같습니다!

2021-04-04 02:22 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +      stitches: Number(event.target?.value),
Q: target이 null이라면 어떻게 되나용 :eyes:

2021-04-04 02:22 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
Q: 왜 마스터 브랜치 리베이스 안하고 머지하셨나요?

2021-04-04 02:23 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
컨플릭트가 있으면 리베이스 안 하고 머지하고 있어요!! 리베이스하면 더 보기 불편해져서 😭

2021-04-04 02:24 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +      stitches: Number(event.target?.value),
<img width="136" alt="스크린샷 2021-04-04 오전 11 24 21" src="https://user-images.githubusercontent.com/22957868/113496809-531c4180-9538-11eb-8767-40658dd48f2a.png">
0이 됩니다!

2021-04-04 02:27 UTC, kimdoori commented on src/pages/CreateDesign/types.ts
> +};
오우 좋아요! 사실 어떤 네이밍으로 할지 고민하다가 단순히 detail 페이지에서 입력 받으니 DetailInputs 이었던 건데.. DesignInputs도 좋습니다~!

2021-04-04 02:40 UTC, kimdoori commented on src/pages/CreateDesign/types.ts
> +};
https://github.com/k-roffle/knitting-frontend/pull/24/commits/5aadd64f2dbdd360e0cf531203b2ba163e1d63f1 제안 감사해요~~ 반영했습니다!

2021-04-04 02:41 UTC, kimdoori commented on src/pages/CreateDesign/recoils.ts
> +    armLength: 0,
감사합니다! 반영했어요~~ https://github.com/k-roffle/knitting-frontend/pull/24/commits/150b791254f3a18ed3ebe5015d0a89f6471b8c1f

2021-04-04 02:44 UTC, YuuRiLee reviewed
작업 감사합니당

2021-04-04 02:44 UTC, YuuRiLee commented on src/pages/CreateDesign/types.ts
> +};
p5: `DesignInput`은 어떤가요 복수기는 한데 뭔가 타입이라 DesignInputs은 어색한 거 같기도 하고 그런 느낌적인 느낌

2021-04-04 02:44 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +  const onChangeName: InputProps['onChange'] = (event) => {
`InputProps['onChange']` 요거 신기하네요

2021-04-04 02:44 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +  const onChangePrice: InputProps['onChange'] = (event) => {
p5: 뭔가 반복되는게 생각보다 많네요 
```
    setCurrentDetailInputsAtom({
      ...currentDetailInputs,
      price: Number(event.target?.value),
    });
```
을 price랑 event를 매개변수로 받는 함수로 빼버리고 싶네요 srp 원칙에 위배가 될까요 🤔

2021-04-04 02:44 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +              value={currentDetailInputs.name}
p3: 비구조화 해주세욤

2021-04-04 02:44 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +                defaultValue={DESIGN.SWEATER}
p5: DESIGN이랑 PATTERN도 비구조화 해주세욤

2021-04-04 02:44 UTC, YuuRiLee commented on src/pages/CreateDesign/types.ts
> +  yarn: string | undefined;
p5: `yarn?: string;`도 되지 않나욤

2021-04-04 02:45 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
음.. 이렇게 하면 커밋 log 그래프가 복잡해질 것 같은데요
저는 작은 feature PR에서는 리베이스해도 어디가 컨플릭이 있었고 잘 고쳐졌는지 혹은 잘못고쳐졌는지 확인하기 쉽다고 생각해서 리베이스하는 것이 더 좋아보이는데 어떻게 생각하시나요?
작은 PR에서 리뷰 볼때의 복잡함과 log 그래프를 볼 때 복잡함을 고민해봤을 때 전자가 좀 더 덜 복잡하다고 생각해서요!

2021-04-04 02:47 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +      stitches: Number(event.target?.value),
그럼 null이 들어갈 수 없는 문자열 데이터 (needle) 같은 경우에는 target이 null이라면 어떻게 되나요?

2021-04-04 02:47 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
어차피 스쿼시 머지해서 크게 상관 없지 않을까용?!

2021-04-04 02:47 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
오잉 스쿼시 머지하기로 했나요??

2021-04-04 02:48 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
따로 정한 적은 없는 것 같은데 저는 요즘 스쿼시 머지를 선호하고 있습니다!

2021-04-04 02:49 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
따로 이야기해서 통일하는게 좋을 것 같아요! 사람마다 선호하는게 워낙 달라서...! 슬랙에서 이야기해보시죠

2021-04-04 02:53 UTC, zoripong requested changes
사소하지만 고쳤으면 좋겠는 하나

2021-04-04 02:53 UTC, zoripong commented on src/pages/CreateDesign/recoils.ts
> +    armholeDepth: 0,
p2: 위에서는 arm-hole-depth로 적혀있는데 여기는 armhole-depth인 것 같아요! 통일해주시면 좋을 것 같습니다!

2021-04-04 03:01 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +  const onChangePrice: InputProps['onChange'] = (event) => {
사실 저번에 구두로 얘기했던 것에 이어서 그렇다고 생각하진 않는데요!
요 방법이 지금은 좀 더 편해서 그 때 결론 지었던... 각 요소마다 리스너 하나씩 추가하는 방식으로 작업한 것입니다!!

요건 조금 더 후에(이 스택에 익숙해진 후..) 고민해봐도 될까요?!

2021-04-04 03:03 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +  const onChangePrice: InputProps['onChange'] = (event) => {
좋습니당

2021-04-04 03:05 UTC, kimdoori commented on src/pages/CreateDesign/types.ts
> +  yarn: string | undefined;
https://github.com/k-roffle/knitting-frontend/pull/24/commits/873f1ddbd4a242af2696e971f406d27af8e66b84 감사합니당!

2021-04-04 03:06 UTC, kimdoori commented on src/pages/CreateDesign/types.ts
> +};
넵! 복수보다는 단수가 더 나은 것 같아 최종적으로 DesignInput으로 변경했어요! https://github.com/k-roffle/knitting-frontend/pull/24/commits/5df7e666af88e30faad9015185334dbef9626d7d

2021-04-04 03:10 UTC, kimdoori commented on src/pages/CreateDesign/recoils.ts
> +    armholeDepth: 0,
힛... 감사합니다! https://github.com/k-roffle/knitting-frontend/pull/24/commits/5c483a800b24b02eee6c49ccf29382111508b2de

2021-04-04 03:34 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +              value={currentDetailInputs.name}
https://github.com/k-roffle/knitting-frontend/pull/24/commits/0ab4b8c015920669314ee92d4472923b2ce5be36 비구조화했습니다요! 아래 리뷰도 여기서 같이 반영했어요!

2021-04-04 03:34 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +      stitches: Number(event.target?.value),
어어아.. target이 null인 경우를 테스트해보기 어려워서 조금 더 방어적으로 변경했습니다!
https://github.com/k-roffle/knitting-frontend/pull/24/commits/9cf9c202e1de6acfdc0fbe8ef50b42317c2e3b8f

중복 줄이고 싶다^ㅜㅠ 요건 추후에..

2021-04-04 03:35 UTC, kimdoori commented on src/pages/CreateDesign/Detail/index.tsx
> +              <FormLabel variant="h5">도안 종류</FormLabel>
리베이스 머지 하기로 결정! ✅ 

요번에 머지한 건 그대로 둘게요! ㅎㅎ 담부터..

2021-04-04 03:35 UTC, kimdoori commented
@zoripong @YuuRiLee 리뷰 감사합니당~~!! 반영 ed!

2021-04-04 04:43 UTC, zoripong approved these changes
👍

2021-04-06 14:16 UTC, YuuRiLee approved these changes
LGTM 💯

2021-04-07 13:17 UTC, merged