[Feat] Pattern 페이지에 inline, block 스타일 버튼으로 변경할 수 있도록 툴바 추가
k-roffle/knitting-frontend pull request #34
Opened 2021-04-17 18:00 UTC by YuuRiLee

## PR 제안 사유

Close #33 

## 주요 변경 기록
- draft-js buttons, static-toolbar plugin인 추가
- DropDown과 DropdownOption 컴포넌트 추가
- draft-js-utils에 block, inline에서 필요한 부분만 추가
- react-draft-wysiwyg를 참조하여 FontSize 컴포넌트 추가
- Pattern 컴포넌트에 inline, block style button 적용

## Code review

### Code review 에서 중점적으로 봐야하는 부분

## Design review

### Design review 에서 중점적으로 봐야하는 부분 / 스크린샷
<img width="1680" alt="스크린샷 2021-04-18 오전 2 52 11" src="https://user-images.githubusercontent.com/26711037/115122097-16008680-9ff1-11eb-9dbd-5d15edacb638.png">
<img width="1680" alt="스크린샷 2021-04-18 오전 2 58 13" src="https://user-images.githubusercontent.com/26711037/115122259-edc55780-9ff1-11eb-97c3-a69ff4bf241c.png">

## 기타 질문 및 특이 사항

2021-04-18 02:42 UTC, zoripong commented on src/pages/CreateDesign/components/DropDown/DropDownOption/index.tsx
> +      }
```suggestion
      onSelect?.(value);
      if (onClick) {
        event.stopPropagation();
        onClick(value);
      }
```

p3: 이렇게 쓸 수 있지 않나요?!

2021-04-18 02:42 UTC, zoripong commented on src/pages/CreateDesign/components/DropDown/index.tsx
> +  children: any;
Q: Unknown 안되나여?

2021-04-18 02:42 UTC, zoripong commented on src/pages/CreateDesign/components/DropDown/index.tsx
> +    };
Q: 아래에서 remove하면 위에 addEventListener가 의미 없어지지 않나여? 🤔

2021-04-18 02:42 UTC, zoripong commented on src/pages/CreateDesign/components/DropDown/index.tsx
> +            return temp;
q3: temp 없이 바로 return 하는 것 어떠신가요?

2021-04-18 02:42 UTC, zoripong commented on src/pages/libs/draftjs-utils/inline.ts
> +  FONTSIZE?: any;
q: unknown 안되나요..? ㅠ_ㅠ

2021-04-18 03:00 UTC, kimdoori reviewed
수고 많으셨습니다~~

2021-04-18 03:07 UTC, kimdoori commented on src/pages/CreateDesign/components/DropDown/DropDownOption/index.tsx
> +  active: boolean;
다른 곳도 이렇게 적용된 거 확인했습니당

2021-04-24 03:51 UTC, YuuRiLee commented on src/pages/CreateDesign/components/DropDown/index.tsx
> +  children: any;
<img width="612" alt="스크린샷 2021-04-24 오후 12 51 33" src="https://user-images.githubusercontent.com/26711037/115946390-cdb6fc00-a4fb-11eb-9ece-1e802ee9e7dc.png">
안됩니당,,

2021-04-24 03:53 UTC, YuuRiLee commented on src/pages/CreateDesign/components/DropDown/index.tsx
> +    };
이벤트 리스너 제거하려고 저렇게 써준겁니다! [참고 링크](https://stackoverflow.com/questions/55360736/how-do-i-window-removeeventlistener-using-react-useeffect)

2021-04-24 04:05 UTC, YuuRiLee commented on src/pages/libs/draftjs-utils/inline.ts
> +  FONTSIZE?: any;
<img width="619" alt="스크린샷 2021-04-24 오후 12 55 55" src="https://user-images.githubusercontent.com/26711037/115946485-6a799980-a4fc-11eb-9f86-545cc0424ec8.png">
sad story,,,

2021-04-24 04:07 UTC, YuuRiLee commented on src/pages/libs/draftjs-utils/block.ts
> + */
https://github.com/jpuri/draftjs-utils/tree/master/js 여기 있는 함수 가져온거라 주석도 같이 가지고 왔는데 지울까요?

2021-04-24 04:14 UTC, YuuRiLee commented on src/pages/libs/draftjs-utils/inline.ts
> +const getStyleAtOffset = (
스타일의 오프셋 크기를 반환하는 함수라 괜찮지 않을까 하는데 어떠신가요?

2021-04-24 04:21 UTC, YuuRiLee commented
@kimdoori @zoripong [해당 커밋](https://github.com/k-roffle/knitting-frontend/pull/34/commits/fb1a81febe785645654d355f43a99a6c702bd458)부터 봐주시고 코멘트 확인 부탁드립니다!

2021-04-24 04:24 UTC, kimdoori commented on src/pages/libs/draftjs-utils/block.ts
> + */
지워도 괜찮을 것 같아요~

2021-04-24 04:26 UTC, kimdoori commented on src/pages/libs/draftjs-utils/inline.ts
> +const getStyleAtOffset = (
👞 마음대로!

2021-04-24 08:05 UTC, YuuRiLee commented
@kimdoori [해당 커밋](https://github.com/k-roffle/knitting-frontend/pull/34/commits/f1ae8743cf052cf4204553694a6ddc0fa8f307b2)부터 봐주세요

2021-04-24 08:08 UTC, kimdoori approved these changes
고생 많으셨습니다~

2021-04-24 08:39 UTC, zoripong commented on src/pages/CreateDesign/components/DropDown/index.tsx
> +  children: any;
ㅠㅠ

2021-04-24 08:44 UTC, zoripong commented on src/pages/libs/draftjs-utils/inline.ts
> +interface ChangeOriginalStyleToNeweStyle {
```suggestion
interface ChangeOriginalStyleToNewStyle {
```
p2: 오타인 것 같아요!

2021-04-24 08:44 UTC, zoripong commented on src/pages/libs/draftjs-utils/inline.ts
> +  }
```suggestion
  if (newStyle == null) {
    editorStateWithNewStyle = editorStateWithToggleOriginalStyle;
  } else {
    editorStateWithNewStyle = RichUtils.toggleInlineStyle(
      editorStateWithToggleOriginalStyle,
      newStyle,
    );
  }
```
p4: if-else 처리 할 때 if에 not 이 안 붙어있는게 개인적으로 좀 더 읽기 편하더라구여

2021-04-24 08:44 UTC, zoripong commented on src/pages/libs/draftjs-utils/inline.ts
> +  FONTSIZE?: any;
so ... sad...

2021-04-24 08:47 UTC, zoripong requested changes
오타 발견쓰

2021-04-28 15:13 UTC, YuuRiLee commented
line-height 수정 전
<img width="462" alt="스크린샷 2021-04-29 오전 12 11 55" src="https://user-images.githubusercontent.com/26711037/116428046-845e0800-a87f-11eb-84e6-dcc7cd7a6a17.png">

line-height 수정 후 
<img width="455" alt="스크린샷 2021-04-29 오전 12 11 28" src="https://user-images.githubusercontent.com/26711037/116427983-74462880-a87f-11eb-909e-cbd293059d2f.png">

@kimdoori @zoripong [해당 커밋](https://github.com/k-roffle/knitting-frontend/pull/34/commits/6be02a962150ce831d0b81cce548d79f4dac9895)부터 봐주세요

2021-05-07 06:05 UTC, kimdoori approved these changes
ㄹㄱㅌㅁ 👍

2021-05-08 08:45 UTC, zoripong commented
ㄹㄱㅌㅁ가 뭐죠.......  🤔

2021-05-08 09:49 UTC, kimdoori commented
> ㄹㄱㅌㅁ가 뭐죠....... 🤔

looks good to me 😉

2021-05-09 10:49 UTC, merged