Resolve #3 초기 router 세팅
k-roffle/knitting-frontend pull request #4
Opened 2021-03-07 06:49 UTC by YuuRiLee

초기 `router`를 세팅합니다

변경 사항
- `import/order`를 설정했습니다.
- `tsconfig` `baseUrl`을 `./src`로 설정했습니다.
- 라우터를 위한 패키지를 추가했습니다.
  - `query-string`, `react-router-dom`, `use-query-params` 패키지
-  `.eslintignore` 파일 추가했습니다.
- 초기 라우터 세팅을 했습니다.
  - `Error404` 페이지
  - `NewDesign/Detail`, `NewDesign/Pattern`, `NewDesign/Review` 페이지

2021-03-10 13:26 UTC, zoripong requested changes

2021-03-10 13:26 UTC, zoripong commented on .eslintrc.json
> +          }
이거 폴더 구조 CONTRIBUTING.md 같은 곳에 적혀있으면 좋을 것 같군요!

2021-03-10 13:26 UTC, zoripong commented on package.json
> +    "use-query-params": "^1.2.0",
query-string이랑 무슨 차이인가용?

2021-03-10 13:26 UTC, zoripong commented on src/pages/NewDesign/index.tsx
> +      <Route path={`${url}/step=3`} component={Review} exact />
step=1, step=2, step=3는 쿼리 파라미터로 들어가야하는 것 아닌가요?

물음표가 빠져서 쿼리파라미터로 관리가 안 될 것 같아요.

2021-03-11 14:22 UTC, YuuRiLee commented on package.json
> +    "use-query-params": "^1.2.0",
` use-query-params` 쓰려면 `query-string` 필요합니담 [깃허브 링크](https://github.com/pbeshai/use-query-params)

2021-03-11 15:02 UTC, YuuRiLee commented on .eslintrc.json
> +          }
문서로 정의하기 보다는 추가되어야 할 경우 상의해서 순서를 정하는 것이 어떨까요

2021-03-11 15:03 UTC, YuuRiLee commented on src/pages/NewDesign/index.tsx
> +      <Route path={`${url}/step=3`} component={Review} exact />
각 페이지 만들지 않고 페이지 하나에 하위 컴포넌트 3개 만들기로 했습니다 [관련 스레드](https://kroffle.slack.com/archives/C01PBRC52DQ/p1615473086023200)

2021-03-13 10:25 UTC, zoripong commented on .eslintrc.json
> +          }
저는 순서 말고, 어떤 디렉토리는 어떤 컴포넌트들이 포함된다에 대한 폴더 구조가 적혀있으면, 처음 보는 사람도 코드 이해하기 쉬울 것 같아서 제안드린거였어용!

2021-03-13 10:26 UTC, zoripong commented on package.json
> +    "use-query-params": "^1.2.0",
use-query-params 이제 안쓰는 것 같은데 그대로 둘 예정이신가요?!

2021-03-13 10:26 UTC, zoripong reviewed
남은 코멘트 한 번만 더 확인해주세요!

2021-03-13 11:34 UTC, YuuRiLee commented on package.json
> +    "use-query-params": "^1.2.0",
App.tsx에서 쓰입니담

2021-03-13 11:40 UTC, YuuRiLee commented on .eslintrc.json
> +          }
`types, utils, components, pages, assets` 각 디렉토리 이름에서 알 수 있다고 생각하는데 어떠신가요?

2021-03-13 13:05 UTC, zoripong approved these changes

2021-03-14 02:57 UTC, kimdoori commented on src/pages/CreateDesign/Review/index.tsx
> +const Detail = (): React.ReactElement => {
Review 가 되어야할 것 같아여!

2021-03-14 02:57 UTC, kimdoori commented on src/pages/Designs/index.tsx
> +      <Route path={`${url}/create`} component={CreateDesign} exact />
트레일링 슬래시 넣어주실 수 있나여?!

2021-03-14 03:15 UTC, YuuRiLee commented
@kimdoori [리뷰 반영](https://github.com/k-roffle/knitting-frontend/pull/4/commits/bdfbff5424f9258ce8fb8d61dc4afe0d4e6ce840) 했습니다

2021-03-14 03:17 UTC, kimdoori approved these changes
감사합니다!!!! 짱!!!

2021-03-14 03:18 UTC, YuuRiLee commented
^ 커밋 정리했습니다

2021-03-14 03:19 UTC, merged