[Design] Detail 페이지 디자인 수정
k-roffle/knitting-frontend pull request #64
Opened 2021-06-26 18:36 UTC by YuuRiLee

## PR 제안 사유

Fix #62 

## 주요 변경 기록
#63 을 베이스로 했습니다 [Fix: float 대문자로 들어가던 것 수정]() 부터 봐주세요

## Code review

### Code review 에서 중점적으로 봐야하는 부분
- float 대문자로 들어가던 것을 수정했습니다
- design 페이지 footer, 상위 margin 간격을 조정했습니다
- input required 속성이 있는 것들 label에 *을 추가했습니다
- kint 이미지를 수정했습니다
- 숫자 input에 문자를 입력할 경우 NaN이 나타나는 문제를 수정했습니다

## Design review

### Design review 에서 중점적으로 봐야하는 부분 / 스크린샷
<img width="922" alt="스크린샷 2021-06-27 오전 3 33 04" src="https://user-images.githubusercontent.com/26711037/123522460-633b5b80-d6f8-11eb-9e56-83af477a5549.png">

## 기타 질문 및 특이 사항

2021-06-27 05:23 UTC, zoripong requested changes

2021-06-27 05:23 UTC, zoripong commented on src/pages/CreateDesign/components/StepProgressBar/index.tsx
> +          <StyledStepLabel StepIconComponent={renderStepIcon}>
Q: `StepIconComponent`는 왜 파스칼케이스인가요?

2021-06-27 05:23 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +  const RequiredChar = (): React.ReactElement => (
```suggestion
  const RequiredMark = (): React.ReactElement => (
```
p4: 는 어떠신가요!

2021-06-27 05:23 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +  );
p4: 앞으로 input에서 계속 쓸 것 같은데 dumbs에 RequiredInput으로 컴포넌트 만들어줘도 좋을 것 같아요!
* 마크 붙여주면서, required=true의 input을 그리는 컴포넌트로요!

2021-06-27 05:23 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length > 1 && Number(value) < 1;
Q: value.length가 1 "이상"이 아닌 "초과"여야 하는게 맞나요?

2021-06-27 05:23 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
>    };
p2: checkPositiveNumber 인데 1 이상의 수가 들어오면 false가 반환될 것 같아요.
함수 명을 바꾸거나 조건식이 아래처럼 변경되어야 할 것 같아요.
```js
    return value.length >= 1 && Number(value) >= 1
```

2021-06-27 05:24 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
>    };
아래에서 0 이하인지 체크하니까 함수명이 바뀌어야 할 것 같은데 함수명이 애매하겠네요.. (0은 음수가 아니라서)
여기 조건을 바꾸고 아래에서 not 연산자를 바꾸는게 나을 것 같기도 해요 🤔

2021-06-27 05:38 UTC, YuuRiLee commented on src/pages/CreateDesign/components/StepProgressBar/index.tsx
> +          <StyledStepLabel StepIconComponent={renderStepIcon}>
컴포넌트라 첫 글자를 대문자로 했어요

2021-06-27 05:45 UTC, YuuRiLee commented
^ main 리베이스 했습니다

2021-06-27 05:50 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
>    };
Number(value) < 0으로 하고 checkNegativeNumber로 바꿀게요

2021-06-27 05:51 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length > 1 && Number(value) < 1;
이상으로 바꿀게욤

2021-06-27 07:55 UTC, YuuRiLee commented
@zoripong [해당 커밋](https://github.com/k-roffle/knitting-frontend/pull/64/commits/c8bc6b3d43fd03b40ee8ee9ee5fab1627ae9fb48) 부터 봐주세요

2021-06-27 08:27 UTC, zoripong reviewed
오 리뷰 반영감사합니다! 근데 하나만 확인해주세요1

2021-06-27 08:27 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length >= 1 && Number(value) < 0;
p3: 0도 가능해질텐데 괜찮을까요? 0코, 0단 이나 길이가 0인 경우는 오면 안 될 것 같아서요!

2021-06-27 08:27 UTC, zoripong commented on src/dumbs/RequiredInput/index.tsx
> +        required
```suggestion
        required={true}
```

p4: 아까는 이렇게 바꾸어주었길래 :eyes:

2021-06-27 08:28 UTC, zoripong commented on src/pages/CreateDesign/components/StepProgressBar/index.tsx
> +          <StyledStepLabel StepIconComponent={renderStepIcon}>
🤔  원래 매개변수에 컴포넌트 받아야하면 파스칼로 쓰나요?

2021-06-27 08:28 UTC, YuuRiLee commented on src/dumbs/RequiredInput/index.tsx
> +        required
required={true}는 생략 가능해서 required로 썼어욤

2021-06-27 08:29 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length >= 1 && Number(value) < 0;
그렇군욤 그럼 checkNegativeNumberOrZero 이렇게 하는게 나을까요 🤔

2021-06-27 08:30 UTC, YuuRiLee commented on src/pages/CreateDesign/components/StepProgressBar/index.tsx
> +          <StyledStepLabel StepIconComponent={renderStepIcon}>
생각해보니 children도 파스칼 아니라 이건 변경해둘게요

2021-06-27 08:34 UTC, zoripong commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length >= 1 && Number(value) < 0;
checkPositive로 하고 사용할 때 not 연산자 붙이는게 이해하기 쉽지 않을까요? :thi

2021-07-03 05:24 UTC, YuuRiLee commented on src/pages/CreateDesign/components/StepProgressBar/index.tsx
> +          <StyledStepLabel StepIconComponent={renderStepIcon}>
<img width="705" alt="스크린샷 2021-07-03 오후 2 24 27" src="https://user-images.githubusercontent.com/26711037/124343944-652a8080-dc0a-11eb-8373-0cd2fffed374.png">
만든 컴포넌트인줄 알았는데 Mui 꺼였군욤,,,

2021-07-03 05:40 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length >= 1 && Number(value) < 0;
근데 그러면 계속 !를 붙여줘야하지 않나요?

2021-07-03 05:43 UTC, YuuRiLee commented on src/pages/CreateDesign/Detail/index.tsx
> +    return value.length >= 1 && Number(value) < 0;
https://github.com/k-roffle/knitting-frontend/pull/64/commits/95e7e4d5bfc10aaa781e39dfb3a44246c6030b51

2021-07-03 05:51 UTC, zoripong commented on src/pages/CreateDesign/components/StepProgressBar/index.tsx
> +          <StyledStepLabel StepIconComponent={renderStepIcon}>
ㄴㅇㄱ !

2021-07-03 05:52 UTC, zoripong approved these changes
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

2021-07-03 05:52 UTC, merged